sonar.projectKey=flowmatix-crm
sonar.projectName=Flowmatix CRM
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.{js,jsx}
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.{js,jsx}

sonar.sourceEncoding=UTF-8

# SonarQube server
sonar.host.url=https://sonar.flowmatix.io
